backend:
  name: git-gateway
  repo: digitalinclusionsac/digitalinclusionsac.org
  branch: cms-dev # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "About Website"
        name: "about-website"
        file: "_data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Website Title"
            name: "title"
            widget: "string"
          - label: "Website Description"
            name: "description"
            widget: "text"
      - label: "Fact and Mission"
        name: "fact-mission"
        file: "_data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Fact Header"
            name: "fact_header"
            widget: "string"
          - label: "Fact Description"
            name: "fact_description"
            widget: "text"
          - label: "Mission Header"
            name: "mission_header"
            widget: "string"
          - label: "Mission Description"
            name: "mission_description"
            widget: "text"
      - label: "Strategies"
        name: "strategies"
        file: "_data/homepage.yml"
        editor:
          preview: false
        fields:
          - label: "Strategies Header"
            name: "strategies_header"
            widget: "string"
          - label: "Strategy 1"
            name: "strategy_one"
            widget: "string"
          - label: "Strategy 1 Detail"
            name: "strategy_one_detail"
            widget: "text"
          - label: "Strategy 2"
            name: "strategy_two"
            widget: "string"
          - label: "Strategy 2 Detail"
            name: "strategy_two_detail"
            widget: "text"
          - label: "Strategy 3"
            name: "strategy_three"
            widget: "string"
          - label: "Strategy 3 Detail"
            name: "strategy_three_detail"
            widget: "text"
  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
