backend:
  name: git-gateway
  repo: digitalinclusionsac/digitalinclusionsac.org
  branch: cms-dev # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'

collections:
  - name: "homepage-content"
    label: "Homepage Content"
    files:
      - label: "Text Sections"
        name: "text-sections"
        file: "_data/sitewide.yml"
        editor:
          preview: false
        fields:
          - label: "Website Title"
            name: "title"
            widget: "string"
          - label: "Website Description"
            name: "description"
            widget: "text"
  - name: "pages"
    label: "Pages"
    folder: "_pages/"
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
